#############################################################################
# Makefile for building: picross
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Mar 1 18:57:11 2010
# Project:  picross.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile picross.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,--hash-style=gnu -Wl,--as-needed
LIBS          = $(SUBLIBS)  -L/usr/lib -lSDL -lSDL_image -lSDL_mixer -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = SDL_rotozoom.cpp \
		main.cpp \
		GB_VideoSystem.cpp \
		GB_TextEngine.cpp \
		GB_System.cpp \
		GB_Sprites.cpp \
		GB_Backgrounds.cpp \
		GB_AudioSystem.cpp \
		Game.cpp \
		Puzzle.cpp 
OBJECTS       = SDL_rotozoom.o \
		main.o \
		GB_VideoSystem.o \
		GB_TextEngine.o \
		GB_System.o \
		GB_Sprites.o \
		GB_Backgrounds.o \
		GB_AudioSystem.o \
		Game.o \
		Puzzle.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		picross.pro
QMAKE_TARGET  = picross
DESTDIR       = 
TARGET        = picross

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: picross.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile picross.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile picross.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/picross1.0.0 || $(MKDIR) .tmp/picross1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/picross1.0.0/ && $(COPY_FILE) --parents SDL_rotozoom.h GB_VideoSystem.h GB_TextEngine.h GB_Definitions.h GB_Backgrounds.h GB_AudioSystem.h GB_System.h GB_Sprites.h GB_Globals.h Game.h GameBlade.h Puzzle.h .tmp/picross1.0.0/ && $(COPY_FILE) --parents SDL_rotozoom.cpp main.cpp GB_VideoSystem.cpp GB_TextEngine.cpp GB_System.cpp GB_Sprites.cpp GB_Backgrounds.cpp GB_AudioSystem.cpp Game.cpp Puzzle.cpp .tmp/picross1.0.0/ && (cd `dirname .tmp/picross1.0.0` && $(TAR) picross1.0.0.tar picross1.0.0 && $(COMPRESS) picross1.0.0.tar) && $(MOVE) `dirname .tmp/picross1.0.0`/picross1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/picross1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

SDL_rotozoom.o: SDL_rotozoom.cpp SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SDL_rotozoom.o SDL_rotozoom.cpp

main.o: main.cpp GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h \
		Game.h \
		Puzzle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

GB_VideoSystem.o: GB_VideoSystem.cpp GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GB_VideoSystem.o GB_VideoSystem.cpp

GB_TextEngine.o: GB_TextEngine.cpp GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GB_TextEngine.o GB_TextEngine.cpp

GB_System.o: GB_System.cpp GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GB_System.o GB_System.cpp

GB_Sprites.o: GB_Sprites.cpp GB_Sprites.h \
		GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GB_Sprites.o GB_Sprites.cpp

GB_Backgrounds.o: GB_Backgrounds.cpp GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GB_Backgrounds.o GB_Backgrounds.cpp

GB_AudioSystem.o: GB_AudioSystem.cpp GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GB_AudioSystem.o GB_AudioSystem.cpp

Game.o: Game.cpp Game.h \
		GameBlade.h \
		GB_Definitions.h \
		GB_Globals.h \
		GB_VideoSystem.h \
		GB_AudioSystem.h \
		GB_Sprites.h \
		GB_Backgrounds.h \
		GB_TextEngine.h \
		GB_System.h \
		SDL_rotozoom.h \
		Puzzle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

Puzzle.o: Puzzle.cpp Puzzle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Puzzle.o Puzzle.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

